title: Hello, world! I'm aBaO 
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://aabao.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: aBaO # add your name
author-img: abao.jpg # add your photo
about-author: 我喜欢分享，想在这个博客空间和大家一起分享我的各种心得 # add description
twitter: # add your Twitter handle
facebook: # add your Facebook handle
github: aaBaO # add your Github handle
linkedin: # add your Linkedin handle
email: abao883@gmail.com # add your Email address

# Disqus
discus-identifier: aaBaO # add your discus identifier

# Tracker
analytics: UA-107318915-1 # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
